# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:36
from __future__ import unicode_literals

import djacket.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(storage=djacket.storage.OverwriteStorage(), upload_to=user.models.user_avatar_path)),
                ('birthdate', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
