def partition_url(path_info):
    """
        Returns sections of a request url path.
    """

    return [part for part in path_info.split('/') if part != ''] # remove '' items generated by spliting the url.
